finances/urls.py
from django.urls import path

from . import views

app_name = 'finances'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('register/', views.UserFormView.as_view(), name='register'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('create_entry/', views.CreateEntry.as_view(), name='create_entry'),
    path('update_entry/<int:pk>', views.UpdateEntry.as_view(), name='update_entry'),
    path('list_entry/', views.ListEntry.as_view(), name='list_entry'),
    path('entries_statement/', views.EntriesStatement.as_view(), name='entries_statement'),
    path('entries_by_category/', views.EntriesByCategory.as_view(), name='entries_by_category'),
    path('delete/<int:pk>/', views.DeleteEntry.as_view(), name='delete_entry'),
]

financial_control/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('finances/', include('finances.urls'))
]

finances/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Sum


class Category(models.Model):

    INCOME = 'IN'
    EXPENSE = 'EX'
    ENTRY_TYPE_CHOICES = (
        (INCOME, 'INCOME'),
        (EXPENSE, 'EXPENSE'),
    )

    entries_type = models.CharField(
        max_length=2,
        choices=ENTRY_TYPE_CHOICES,
        default= EXPENSE,
    )

    description = models.CharField(max_length=100)

    def __str__(self):
        return '%s' % (self.description)


class EntryManager(models.Manager):

    def get_entries(self, user, month, year, limit, entry_type):
        try:
            return self.order_by('entry_date').filter(
                agent=user, category__in=Category.objects.filter(entries_type__in=entry_type),
                entry_date__month=month, entry_date__year=year
                )[:limit]
        except ObjectDoesNotExist:
            return None

    def get_incomes(self, user, month, year, limit):
        return self.get_entries(user, month, year, limit, [('IN')])

    def get_expenses(self, user, month, year, limit):
        return self.get_entries(user, month, year, limit, [('EX')])

    def get_all_entries(self, user, month, year, limit):
        return self.get_entries(user, month, year, limit, [('IN'), ('EX')])

    def get_entries_amount(self, user, entries):
        return entries.aggregate(Sum('amount'))
    
    def get_amount_expenses_by_category(self, user, month, year, limit):
        expenses = self.get_expenses(user, month, year, limit)
        return expenses.order_by('category__description').values('category__description').annotate(Sum('amount'))
    
    def get_expenses_by_category(self, user, month, year, limit):
        expenses = self.get_expenses(user, month, year, limit).values('category__description', 'description', 'amount', 'entry_date')
        return expenses.order_by('category__description', 'entry_date')
        

class Entry(models.Model):
    agent = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)
    amount = models.FloatField()
    entry_date = models.DateField(default=timezone.now)

    objects = EntryManager()

    def __str__(self):
        return 'Agent: %s, Category: %s, Description: %s, Amount: %s, Entry Date: %s' % (
            self.agent.id, self.category.description, self.description, self.amount, self.entry_date)

finances/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Entry, Category
from django.utils import timezone


class UserForm(forms.ModelForm):
    password = forms.CharField(label='Senha',widget=forms.PasswordInput)
    email = forms.CharField(label='Email')
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class EntryForm(forms.ModelForm):
    description = forms.CharField(label='Descrição', required=True)
    amount = forms.FloatField(label='Valor', required=True, min_value=0.1)
    entry_date = forms.DateField(label='Data', initial=timezone.now, required=True)

    def __init__(self, *args, **kwargs):
        entry_type = kwargs.pop('entry_type')
        super().__init__(*args, **kwargs)

        self.fields['category'].label = 'Categoria'
        self.fields['category'].queryset = Category.objects.order_by('description').filter(entries_type=entry_type)
    
    class Meta:
        model = Entry
        fields = ['category', 'description', 'amount', 'entry_date']

finances/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.views.generic import View, ListView
from .forms import UserForm, EntryForm
from .models import Entry
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
import datetime
from django.utils.dates import MONTHS


class IndexView(LoginRequiredMixin, View):
    template_name = 'finances/index.html'
    login_url = 'finances:login_user'

    def get(self, request):
      return get_list_entries(request, 5, self.template_name)


class UserFormView(View):
    form_class = UserForm
    template_name = 'finances/registration_form.html'
    
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return render(request, 'finances/index.html')

        return render(request, self.template_name, {"form": form})


class CreateEntry(LoginRequiredMixin, CreateView):
    login_url = "finances:login_user"
    template_name = 'finances/entry_form.html'
    success_url = reverse_lazy('finances:list_entry')
    form_class = EntryForm
    
    def form_valid(self, form):
        entry = form.save(commit=False)
        entry.agent = self.request.user
        entry.save()
        return super(CreateEntry, self).form_valid(form)
        
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['entry_type'] = self.request.GET.get('entry_type', 'EX')
        return kwargs


class ListEntry(LoginRequiredMixin, View):
    template_name = 'finances/list_entry.html'
    login_url = 'finances:login_user'

    def get(self, request):
        return get_list_entries(request, None, self.template_name)
     
    def post(self, request): 
        return get_list_entries(request, None, self.template_name) 


class EntriesStatement(LoginRequiredMixin, View):
    template_name = 'finances/entries_statement.html'
    login_url = "finances:login_user"

    def get(self, request):
        return get_list_entries(request, None, self.template_name)    


class EntriesByCategory(LoginRequiredMixin, View):
    template_name = 'finances/entries_by_category.html'
    login_url = "finances:login_user"

    def get(self, request):
        return get_list_entries(request, None, self.template_name)    

        
class UpdateEntry(LoginRequiredMixin, UpdateView):
    login_url = 'finances:login_user'
    template_name = 'finances/entry_form.html'
    form_class = EntryForm
    model = EntryForm.Meta.model
    success_url = reverse_lazy('finances:list_entry')

    def form_valid(self, form):
        entry = form.save(commit=False)
        entry.agent = self.request.user
        entry.save()
        return super(UpdateEntry, self).form_valid(form)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['entry_type'] = self.request.GET.get('entry_type', 'EX')
        return kwargs


class DeleteEntry(LoginRequiredMixin, DeleteView):
    login_url = 'finances:login_user'
    model = Entry
    success_url = reverse_lazy('finances:list_entry')


def login_user(request):
        if request.method == "POST":
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                
                return get_list_entries(request, 5, 'finances/index.html')        
            else: 
                return render(request, 'finances/login.html', {'error_message': 'Usuário ou senha inválidos'})
    
        else:
            return render(request, 'finances/login.html')


def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    return render(request, 'finances/login.html', {"form":form})


def delete_entry(request, entry_id):
    entry = Entry.objects.get(pk=entry_id)
    entry.delete()
    return render(request, 'finances/list_entry.html')
    

def get_list_entries(request, limit, template_name):
    entry_type = request.GET.get('entry_type', 'all')
    month = int(request.POST.get('month', datetime.date.today().month))
    year = int(request.POST.get('year', datetime.date.today().year))
    incomes = Entry.objects.get_incomes(request.user,  month, year, limit)
    expenses = Entry.objects.get_expenses(request.user, month, year, limit)
    all_entries = Entry.objects.get_all_entries(request.user, month, year, None)
    total_incomes = Entry.objects.get_entries_amount(request.user, incomes)
    total_expenses = Entry.objects.get_entries_amount(request.user, expenses)
    category_amount = Entry.objects.get_amount_expenses_by_category(request.user, month, year, None) 
    expenses_by_category = get_list_expenses_by_category(request, limit, month, year)

    context = {
        'incomes': incomes,
        'expenses': expenses,
        'total_incomes': total_incomes,
        'total_expenses': total_expenses,
        'months': MONTHS.items(),
        'current_month': month,
        'years': get_years(year, 5),
        'current_year': year,
        'all_entries': all_entries,
        'entry_type': entry_type,
        'entries_by_category': expenses_by_category,
        'category_amount' : category_amount,
    }
    
    return render(request, template_name, context)


def get_years(current_year, limit):
    years = []
    for i in range(current_year - limit, current_year + limit):
        years.append(i)
    return years


def get_list_expenses_by_category(request, limit, month, year):
    expenses =  Entry.objects.get_expenses_by_category(request.user, month, year, None) 

    expenses_by_category = {}
    
    for result in expenses:
        key = result['category__description']
        if result['category__description'] in expenses_by_category:
            expenses_by_category[result['category__description']].append([
            result['entry_date'],
            result['description'],
            result['amount']
            ])
        else: 
            expenses_by_category.setdefault(key, [])
            expenses_by_category[key].append([
            result['entry_date'],
            result['description'],
            result['amount']
            ])
                

    return expenses_by_category

finances/templates/finances/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Finanças{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/entries.css' %}">
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">

            <!-- Header -->

            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'finances:index' %}">Finanças</a></li>
                    <li><a href="{% url 'finances:list_entry' %}">Lançamentos</a></li>
                    <li><a href="{% url 'finances:entries_statement' %}">Extrato</a></li>
                    <li><a href="{% url 'finances:entries_by_category' %}">Resumo de despesas</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right" class="nav-buttons" style="display: flex; align-items: center">
                    <li>
                        <form action="{% url 'finances:create_entry'%}" method="get" style="display: inline;">
                            <input type="hidden" name="entry_type" value="IN" />
                            <button type="submit" class="btn btn-default btn-sm" style="background-color: #101010; color: #9d9d9d; margin-right: 1rem">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Adicionar receita</button>
                        </form>
                    </li>

                    <li>
                        <form action="{% url 'finances:create_entry'%}" method="get" style="display: inline;">
                            <input type="hidden" name="entry_type" value="EX" />
                            <button type="submit" class="btn btn-default btn-sm" style="background-color: #101010; color: #9d9d9d;">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Adicionar despesa</button>
                        </form>
                    </li>

                    <li>
                        <a href="{% url 'finances:logout_user' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Sair
                        </a>
                    </li>
                </ul>
            </div>

        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

finances/templates/finances/base_anonymous.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Finanças{% endblock %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
    
            <!-- Header -->
    
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'finances:index' %}">Finanças</a></li>
                </ul> 
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'finances:register' %}">
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; Cadastrar
                        </a>
                    </li>
                    
                </ul>
            </div>
    
        </div>
    </nav>
{% block body %}
{% endblock %}
</body>
</html>

finances/templates/finances/create_entry.html
{% extends 'finances/base_anonymous.html' %}
{% block title %}Create Entry{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3>Add a New Entry</h3>
          {% if error_message %}
          <p><strong>{{ error_message }}</strong></p>
          {% endif %}
          <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'finances/form_template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

finances/templates/finances/entries_statement.html
{% extends 'finances/base.html' %}
{% load format_currency %}
{% load get_sum %}
{% block title %}Extrato{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="filter">
        <h3>Extrato de Lançamentos - {{current_month}}/{{current_year}}</h3>
        <form class="form-horizontal" role="form" action="{% url 'finances:entries_statement'%}" method="get" enctype="multipart/form-data">
            <label class="radio-inline">
                <input type="radio" name="entry_type" value="all"  {% if entry_type == 'all'%}checked="checked" {% endif %}>Tudo
            </label>
            <label class="radio-inline"><input type="radio" name="entry_type" value="income" {% if entry_type == 'income'%}checked="checked" {% endif %}>Entrada</label>
            <label class="radio-inline"><input type="radio" name="entry_type" value="expense"  {% if entry_type == 'expense'%}checked="checked" {% endif %}>Saída</label>
            <div class="button-filter">
                <button type="submit" class="btn btn-success">Filtrar</button>
            </div>
        </form>
    </div>

    <table>
        <tr>
            <th>Data</th>
            <th>Categoria</th>
            <th>Descrição</th>
            <th>Valor(R$)</th>
        </tr>
        {% if entry_type == 'income' %}
            {% for entry in incomes %}
            <tr>
                <td>{{entry.entry_date}}</td>
                <td>{{entry.category.description}}</td>
                <td>{{entry.description}}</td>
                <td class= "income">{{entry.amount|format_currency}}</td>
            </tr>
            {% endfor %}
        {% elif entry_type == 'expense' %}
            {% for entry in expenses %}
            <tr>
                <td>{{entry.entry_date}}</td>
                <td>{{entry.category.description}}</td>
                <td>{{entry.description}}</td>
                <td class= "expense">{{entry.amount|format_currency}} - </td>
            </tr>
            {% endfor %}
        {% else %}
            {% for entry in all_entries %}
            <tr>
                <td>{{entry.entry_date}}</td>
                <td>{{entry.category.description}}</td>
                <td>{{entry.description}}</td>
                {%if entry.category.entries_type == 'EX'%}
                    <td class="expense">{{entry.amount|format_currency}} -</td>
                {% else %}
                    <td class="income">{{entry.amount|format_currency}}</td>
                {% endif%}
            </tr>
            {% endfor %}
        {% endif %}
    </table>
    <div class="container-fluid">
        <h3>Resumo</h3>
        <br />
        <div class="row">
            <div class="col-sm-3">Entrada</div>
            <div class="col-sm">
                {{total_incomes.amount__sum|format_currency_symbol}}
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">Saída</div>
            <div class="col-sm"> {{total_expenses.amount__sum|format_currency_symbol}} </div>
        </div>
        <div class="row">
            <div class="col-sm-3">Saldo</div>
            <div class="col-sm">{{total_incomes.amount__sum|get_balance:total_expenses.amount__sum|format_currency_symbol}} </div>
        </div>
    </div>
</div>

{% endblock %}

finances/templates/finances/entry_form.html
{% extends 'finances/base.html' %}
{% block title %}Adicionar lançamento{% endblock %}

{% block body %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-7">
      <div class="panel panel-default">
        <div class="panel-body">
          <h3>Adicionar lançamento</h3>
          {% if error_message %}
          <p><strong>{{ error_message }}</strong></p>
          {% endif %}
          <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include 'finances/form_template.html' %}
            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Salvar</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

finances/templates/finances/index.html
{% extends 'finances/base.html' %}
{% load format_currency %}
{% block title %}Início{% endblock %}
{% block body %}

{% if incomes %}
<div class="container-fluid">
    <h3>Receitas {{total_incomes.amount__sum|format_currency_symbol}}</h3>
    {% for income in incomes %}
    <div class="row">
        <div class="col-sm-3">
            {{income.category.description}}
        </div>
        <div class="col-sm-3">
            {{income.description}}
        </div>
        <div class="col-sm-3">
            {{income.amount|format_currency_symbol}}
        </div>
         
        <form action="{% url 'finances:update_entry' income.id %}" method="get" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="income_id" value="{{ income.id }}" />
            <input type="hidden" name="entry_type" value="IN"/>
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-edit"></span>
            </button>
        </form>
        <form action="{% url 'finances:delete_entry' income.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="income_id" value="{{ income.id }}" />
            <button type="submit" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-trash"></span>
            </button>
        </form>
    </div>
    {% endfor %}
    {% else %}
        <h3> Você não possui receitas </h3>
    {% endif %}
        <a href="{% url 'finances:list_entry' %}"> <span class="glyphicon glyphicon-plus"></span>&nbsp;Ver mais</a>
    
    {% if expenses %}
        <h3>Despesas {{total_expenses.amount__sum|format_currency_symbol}}</h3>
        {% for expense in expenses %}
        <div class="row">
            <div class="col-sm-3">
                {{expense.category.description}}
            </div>
            <div class="col-sm-3">
                {{expense.description}}
            </div>
            <div class="col-sm-3">
                {{expense.amount|format_currency_symbol}}
            </div>
            <form action="{% url 'finances:update_entry' expense.id %}" method="get" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="expense_id" value="{{ expense.id }}" />
                <input type="hidden" name="entry_type" value="EX"/>
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-edit"></span>
                </button>
            </form>
            <form action="{% url 'finances:delete_entry' expense.id %}" method="post" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="expense_id" value="{{ expense.id }}" />
                <button type="submit" class="btn btn-default btn-sm">
                    <span class="glyphicon glyphicon-trash"></span>
                </button>
            </form>
        </div>
        {% endfor %}
    {% else %}
    <h3> Você não possui despesas </h3>
    {% endif %}
    <a href="{% url 'finances:list_entry' %}"> <span class="glyphicon glyphicon-plus"></span>&nbsp;Ver mais</a>
</div>
{% endblock %}

finances/templates/finances/list_entry.html
{% extends 'finances/base.html' %}
{% block title %}Visão Geral{% endblock %}
{% load format_currency %}
{% block body %}

<div class="container-fluid">
    <h3>Detalhamento de lançamentos</h3>
    <div class="row">
        <div class="col-sm-10 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">   
                    <form class="form-horizontal" role="form" action="{% url 'finances:list_entry'%}" method="post" enctype="multipart/form-data" style="display: flex; justify-content: center; align-items: center;">
                        {% csrf_token %}
                        <div class="col-sm-3">
                            <label for="id_month">Mês:</label>
                            <select id="id_month"name="month">
                                {% for month in months %}
                                <option value="{{month.0}}"
                                {% if month.0 == current_month%}selected="selected"{% endif %}>{{month.1}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <label for="id_year">Ano:</label>
                            <select name="year" id="id_year">
                                {% for year in years %}
                                <option value="{{year}}"
                                {% if year == current_year%}selected="selected"{% endif %}>{{year}}</option>
                                {% endfor %}
                            </select>
                        </div>
                            
                        <div class="col-sm-2">
                            <button type="submit" class="btn btn-default btn-md">
                                <span class="glyphicon glyphicon-search"></span>&nbsp;</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    {% if incomes %}
        <div class="container-fluid">
            <h3>Receitas {{total_incomes.amount__sum|format_currency_symbol}}</h3>
            {% for income in incomes %}
            <div class="row">
                <div class="col-sm-3">
                    {{income.category.description}}
                </div>
                <div class="col-sm-3">
                    {{income.description}}
                </div>
                <div class="col-sm-3">
                    {{income.amount|format_currency_symbol}}
                </div>
                 
                <form action="{% url 'finances:update_entry' income.id %}" method="get" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="income_id" value="{{ income.id }}" />
                    <input type="hidden" name="entry_type" value="IN"/>
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-edit"></span>
                    </button>
                </form>
                <form action="{% url 'finances:delete_entry' income.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="income_id" value="{{ income.id }}" />
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
            </div>
            {% endfor %}
            {% else %}
                <h3> Você não possui receitas </h3>
            {% endif %}
            
            {% if expenses %}
                <h3>Despesas {{total_expenses.amount__sum|format_currency_symbol}}</h3>
                {% for expense in expenses %}
                <div class="row">
                    <div class="col-sm-3">
                        {{expense.category.description}}
                    </div>
                    <div class="col-sm-3">
                        {{expense.description}}
                    </div>
                    <div class="col-sm-3">
                        {{expense.amount|format_currency_symbol}}
                    </div>
                    <form action="{% url 'finances:update_entry' expense.id %}" method="get" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="expense_id" value="{{ expense.id }}" />
                        <input type="hidden" name="entry_type" value="EX"/>
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-edit"></span>
                        </button>
                    </form>
                    <form action="{% url 'finances:delete_entry' expense.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="expense_id" value="{{ expense.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                </div>
                {% endfor %}
            {% else %}
            <h3> Você não possui despesas </h3>
            {% endif %}
        </div>

    {% endblock %}
</div>

finances/templates/finances/login.html
{% extends 'finances/base_anonymous.html' %}
{% block title %}Entrar{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Entrar</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'finances:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Usuário:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="100" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Senha:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="100" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Entrar</button>
                            </div>
                        </div>
                    </form>
                    <h4> Não possui uma conta?  <a href="{% url 'finances:register' %}">Clique aqui</a> para cadastrar.</h4>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}